### ISSUE TITLE
Feedback MVP

### ISSUE THREAD

**Issue by mattab** [innocraft/plugin-InvalidateReports#1]
* [x] I tried a real use case, creating [this custom report](https://demo2.piwik.org/index.php?module=CoreHome&action=index&idSite=13&period=month&date=today&updated=1#?idSite=13&period=day&date=2017-11-15&category=CustomReports_CustomReports&subcategory=20), then invalidating reports for Site ID 13 on demo2 (a small site) and then running core:archive. It went over site 13 as expected. But the Custom reports I created still shows "no data". Can you investigate why the report is not showing data in that case? 

* [x] In the messages, add a link to the user guides on `Custom Reports`, `Funnel`, and on `importing new visitor logs` to https://piwik.org/log-analytics/
* [x] Need to change plugin.json with InnoCraft (i just moved the plugin there)
* [x] and file headers
* [x] Segment names and values appear encoded (whereas they display fine in the standard segment selector)
![encoding](https://user-images.githubusercontent.com/466765/32866466-e2955430-cacc-11e7-87fd-3a70ac326748.png)

* [x] Improve readme, bit more descriptive, eg. put at least the same useful text as displayed in the UI (w/ the links) + a link to http://piwik.org/faq/how-to/faq_155/
* [x] When printing message from API, seems maybe some line breaks are missing? would be good to keep the line breaks

![line breaks missing](https://user-images.githubusercontent.com/466765/32866789-435b8798-cace-11e7-930f-f46b75c7b225.png)

**Comment by sgiehl** [comment]
Plugin should be adjusted according to your suggestions. Feel free to add some more stuff to the README.
The custom reports hadn't been reprocessed as there was a small bug causing invalidation of not all periods. Uploaded new version of the plugin to demo2 and checked that again. Reports are now processed correctly.

**Comment by mattab** [comment]
Now it's working :+1: 

* When changing the website in the selector, the list of segment does not refresh below
* (when selecting "All websites" then I suppose only websites visible to "All websites" should be shown?)
 * In the popover instead of writing segment description, write the segment name 
* Line breaks are missing from the API output. Maybe the line breaks are not there in the original API output and should be fixed in core though?
* Forgot to mention it in the specs, but ideally we'd also have a "Choose how far back to invalidate data" with a selector "Invalidate all historical data" / "Invalidate last 2 years" / "Invalidate last 12 month"  / "Invalidate last 6 months" 
* Add a screenshots/ so it shows up in the marketplace

**Comment by sgiehl** [comment]
> Line breaks are missing from the API output. Maybe the line breaks are not there in the original API output and should be fixed in core though?

If so that needs to be adjusted in https://github.com/piwik/piwik/blob/3.x-dev/core/Archive/ArchiveInvalidator/InvalidationResult.php#L45-L54

**Comment by mattab** [comment]
Yes looks like a `\n` will need to be added?

**Comment by sgiehl** [comment]
>  When changing the website in the selector, the list of segment does not refresh below
>  (when selecting "All websites" then I suppose only websites visible to "All websites" should be shown?)

Changed that. Segments available for all websites will be shown always now, and segments for specific sites only when that site was selected...

**Comment by sgiehl** [comment]
Closing this now. Line break for API output needs to be added in core. Will create a PR for that later
