### ISSUE TITLE
JavaScript Error with Matomo 4.0.5

### ISSUE THREAD

**Issue by dieisraels** [innocraft/plugin-InvalidateReports#15]
I get a JavaScript error on the Invalidate reports page with the plugin Invalidate Reports 4.0.1 and Matomo 4.0.5:

![image](https://user-images.githubusercontent.com/988359/102259992-1b997300-3f10-11eb-9eaa-5ba636b3e167.png)

This prevents invalidation from being set up.

**Comment by tsteur** [comment]
I can't reproduce this one @dieisraels  Did you maybe only just enable the plugin? What browser are you using? Any chance you could paste the output from the system report (it's in the left menu in the admin). The report should be anonymised. Mostly we're interested in the list of installed plugins

**Comment by dieisraels** [comment]
I reinstalled the plugin, but the same error.

Here is the system report (Ich habe eine manuelle Änderung in CronArchive.php vorgenommen. Siehe: https://github.com/matomo-org/matomo/pull/16947):

# Mandatory checks

## PHP-Version >= 7.2.5: ✔ 7.3.25


## PDO Erweiterung: ✔ 


## PDO\MYSQL Erweiterung: ✔ 


## MYSQLI Erweiterung: ✔ 


## Weitere erforderliche Anforderungen: ✔ zlib ✔ SPL ✔ iconv ✔ json ✔ mbstring ✔ Reflection


## Erforderliche Funktionen: ✔ debug_backtrace ✔ eval ✔ hash ✔ gzcompress ✔ gzuncompress ✔ pack


## Benötigte PHP Konfiguration (php.ini): ✔ session.auto_start = 0 ✔ max_execution_time = 0 OR >= 30


## Verzeichnisse mit Schreibzugriff: ✔ $DOC_ROOT/tmp ✔ $DOC_ROOT/tmp/assets ✔ $DOC_ROOT/tmp/cache ✔ $DOC_ROOT/tmp/climulti ✔ $DOC_ROOT/tmp/latest ✔ $DOC_ROOT/tmp/logs ✔ $DOC_ROOT/tmp/sessions ✔ $DOC_ROOT/tmp/tcpdf ✔ $DOC_ROOT/tmp/templates_c



# Optional checks

## Dateiintegrität: ⚠ Warning: Der Datei-Integritätscheck ist fehlgeschlagen und hat ein paar Fehler gemeldet. Du solltest die Probleme beheben und diese Seite neuladen, bis sie keine Fehler mehr anzeigt.<br/><br/><pre style="overflow-x: scroll;max-width: 600px;">Die nachfolgenden Fehler könnten durch einen teilweise oder gänzlich fehlgeschlagenen Upload der Matomo-Dateien entstanden sein.
--> Versuche die Matomo-Dateien im BINARY-Modus neu hochzuladen. <--<br/>
Unterschiedliche Dateigröße: $DOC_ROOT/core/CronArchive.php (erwartete Größe: 49111, gefunden: 49122)</pre>


## Tracker-Status: ✔ 


## Speicherlimit: ✔ 512M


## Zeitzone: ✔ 


## Öffnen einer URL: ✔ curl


## PageSpeed deaktiviert: ✔ 


## GD > 2.x + Freetype (graphics): ✔ 


## Andere Erweiterungen: ✔ json ✔ libxml ✔ dom ✔ SimpleXML


## Andere Funktionen: ✔ shell_exec ✔ set_time_limit ✔ mail ✔ parse_ini_file ✔ glob ✔ gzopen ✔ md5_file


## Dateisystem: ✔ 


## Cron einrichten - Prozesse via CLI steuern: nicht unterstützt (optional)


## Letzter erfolgreicher Abschluss der Archivierung: ✔ Der Archivierungsprozess wurde vor 01:05:44 erfolgreich abgeschlossen.


## Datenbankfähigkeiten: ✔ UTF8mb4 charset ⚠ Warning: LOAD DATA INFILE<br/>Die Benutzung von LOAD DATA INFILE erhöht die Geschwindigkeit des Matomo Archivierungsprozesses erheblich. Um dies für Matomo verfügbar zu machen, setzen Sie bitte eine neuere PHP & MySQL Software ein und stellen Sie sicher, dass der gewählte Datenbankbenutzer das FILE Recht besitzt.<br/>Falls Ihr Matomo Server Websites mit erhöhtem Verkehrsaufkommen (z.B.: > 100 000 Seiten pro Monat) verarbeiten muss, empfehlen wir dieses Problem zu beheben.<br/><strong>Fehler:</strong> LOAD DATA INFILE failed... Error was: <br/>  Try #1: LOAD DATA INFILE : SQLSTATE[28000]: Invalid authorization specification: 1045 Access denied for user 'anonmyzed'@'localhost' (using password: YES)[28000],<br/>  Try #2: LOAD DATA LOCAL INFILE : SQLSTATE[42000]: Syntax error or access violation: 1148 The used command is not allowed with this MariaDB version[42000]<br/>Troubleshooting: <a target="_blank" rel="noreferrer noopener" href="https://matomo.org/faq/troubleshooting/#faq_194">FAQ on matomo.org</a> ✔ CREATE TEMPORARY TABLES ✔ Changing transaction isolation level


## Maximale Packetgröße: ✔ 


## Erzwungene SSL Verbindung: ✔ 


## Standorterkennung: ✔ 


## Update über HTTPS: ✔ 


## Schreibbarer JavaScript-Tracker ("/matomo.js"): ✔ 



# Informational results

## Matomo Version: 4.0.5


## Matomo Update History: 4.0.4,3.14.1,


## Matomo Install Version: 3.14.0


## PHP_OS: Linux


## PHP_BINARY: /opt/plesk/php/7.3/sbin/php-fpm


## PHP SAPI: fpm-fcgi


## Timezone Version: 0.system


## PHP Timezone: UTC


## PHP Time: 1608062218


## PHP Datetime: 2020-12-15 19:56:58


## PHP Disabled functions: opcache_get_status


## PHP INI max_execution_time: 120


## PHP INI post_max_size: 8M


## PHP INI max_input_vars: 10000


## PHP INI zlib.output_compression: 


## Curl Version: 7.29.0, NSS/3.44


## Suhosin Installed: 0


## DB Prefix: matomo_


## DB Charset: utf8mb4


## DB Adapter: PDO\MYSQL


## MySQL Version: 10.2.33-MariaDB


## Num Tables: 288


## Browser Segment Archiving Enabled: 1


## Development Mode Enabled: 0


## Internet Enabled: 1


## Multi Server Environment: 0


## Custom User Path: 0


## Custom Include Path: 0


## Plugins Activated: API, Actions, Annotations, BulkTracking, Contents, CoreAdminHome, CoreConsole, CoreHome, CorePluginsAdmin, CoreUpdater, CoreVisualizations, CustomDimensions, CustomJsTracker, DBStats, Dashboard, DevicePlugins, DevicesDetection, Diagnostics, Ecommerce, Events, GeoIp2, Goals, Heartbeat, ImageGraph, Installation, Intl, IntranetMeasurable, InvalidateReports 4.0.1, LanguagesManager, Live, Login, MarketingCampaignsReporting 4.0.4, Marketplace, MobileMessaging, Monolog, Morpheus, MultiSites, Overlay, PagePerformance, PrivacyManager, ProfessionalServices, Provider, Proxy, QueuedTracking 4.0.2, Referrers, Resolution, RssWidget, SEO, ScheduledReports, SecurityInfo 4.0.1, SegmentEditor, SitesManager, Tour, Transitions, TwoFactorAuth, UserCountry, UserCountryMap, UserId, UserLanguage, UsersManager, VisitFrequency, VisitTime, VisitorInterest, VisitsSummary, WebsiteMeasurable, Widgetize


## Plugins Deactivated: CustomVariables, Feedback, Insights, MobileAppMeasurable, TagManager


## Plugins Invalid: 


## Server Info: Apache


## Had visits in last 1 day: 1


## Had visits in last 3 days: 1


## Had visits in last 5 days: 1


## Archive Time Last Started: 1608058020


## Archive Time Last Finished: 1608058274


## Num invalidations: 1 queued, 1 in progress


## User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36


## Browser Language: de,en-us,en


## Anonymize Referrer: 


## Do Not Track enabled: 1

**Comment by tsteur** [comment]
Thanks for this @dieisraels I can actually reproduce it when I disable development mode (and merge assets).

Couldn't quickly figure out what is happening there. @sgiehl can you have a look into this?

**Comment by sgiehl** [comment]
Sorry, I'm not able to reproduce that. Tried it with and without development mode and merged assets

**Comment by tsteur** [comment]
Does it maybe help to disable these plugins?

CustomVariables, Feedback, Insights, MobileAppMeasurable, TagManager

**Comment by sgiehl** [comment]
No. Still works as expected 🤷

**Comment by dieisraels** [comment]
It now works again for me. I didn't change anything else except switching from PHP 7.3.25 to PHP 8.0.0!? And I have invalidated and recalculated some segments via the CLI.

**Comment by tsteur** [comment]
👍 I see on demo it works for us as well. Turns out when I disable developer mode then actually all screens in Matomo trigger the error I got. Might be some other custom plugin that triggers the different error for me.

Glad it works now @dieisraels wonder if it was maybe some cache problem or something.
