### ISSUE TITLE
Database changes in the current month

### ISSUE THREAD

**Issue by matomoto** [innocraft/plugin-InvalidateReports#6]
In relation to this issue: https://github.com/matomo-org/matomo/issues/3385

I have a PHP script with which I can delete all database entries of a visitor via visitorid in the current month (only). The problem is that the data of the (unique) visitors and (unique) pageviews remain untouched. Correcting this data together with my PHP script is next to impossible. Rather, it is possible the next day, since the database is cleaned up the next day and only one value per last day is saved. But even this is difficult and I do not have enough knowledge of the matter.
Now the plugin InvalidateReports comes into play. The question is to what extent it can be useful. If it can not correct in the current day or month, then at least last month. At least it would be a start to this problem.
Perhaps it is possible to record a marker for the current month, which will then renew the data after archiving.

**Comment by mattab** [comment]
Yes, this is exactly what this plugin is for :+1:
