### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by tassoman** [innocraft/plugin-InvalidateReports#68]
Any idea under which license this plugin is released? :thinking: 
Our company it's interested to fork and, eventually contribute.

**Comment by sgiehl** [comment]
It should be under GPL v3+. Maybe @tsteur can quickly confirm.

**Comment by tassoman** [comment]
I found notation in the marketplace page, so means [it's noted into json file](https://github.com/innocraft/plugin-InvalidateReports/blob/feeccdd29794aaff0655f2c084f8b3641d529e81/plugin.json#L6). BTW license should be also provided with souce code, didn't found it.

**Comment by tsteur** [comment]
It should be under GPL v3+ 👍  As you mentioned it's noted in the json file and also the php headers: https://github.com/innocraft/plugin-InvalidateReports/blob/5.x-dev/Menu.php#L6

Be good to add the license file indeed 👍
