### ISSUE TITLE
Prevent users from invalidating too many reports

### ISSUE THREAD

**Issue by mattab** [innocraft/plugin-InvalidateReports#8]
Recently a user has invalidated too much data in the system.This caused a lot of trouble as re-processing would have taken weeks. So we need to add messaging / warnings, to prevent this from happening again ideally.

Maybe the UI could inform users:

* How many archives will be invalidated eg. `15,456 archives will be invalidated. `
* and maybe if more than X archives to  invalidate (no idea what a good number would be, maybe 100 archives?), we could warn users before it happens eg. "As you are invalidating a lot of archives,  warn users it may take several hours (or more) to reprocess all these reports. Are you sure you want to continue?"
* and also when "All websites" is selected, issue a big warning "Are you sure you want to invalidate all websites reports? " 

Do you have any other thought? 

this plugin is currently very valuable when used with Custom Reports. it's important to prevent this tool from breaking the archiving :+1:

**Comment by tsteur** [comment]
I don't think it will prevent too much.
* Most users won't even know what an `archive` is.
* Most users won't know whether the number of archives is high or low. Even the number of archives doesn't mean much if it is high traffic vs low traffic site. 
* Most users would not know what the outcome of that is (meaning how long it will take to rearchive, or whether this could be actually a problem or not)
* Most users will just confirm anyway
* Most users won't even really have basically another choice if they want to get the reports reprocessed for certain time frame. 
* Also 100 archives may be quick to archive or not. 

Asking in general to confirm this action may be fine and can't hurt. The text should be improved and recommend to only invalidate as many dates as needed for example for as many sites as needed. Could also explain for high traffic sites (maybe we mention > 10M pageviews a day or so) it may take a long time. 

In general, I think the pretty much only fix for this is to have the invaliding of a per-report or per-plugin basis as discussed couple times. And ideally for custom reports etc those reports are re-processed basically directly in the next archive run. 

If there is a high website traffic, I would recommend users in general to not use the UI but only do it on the command line so only sysadmins have access. An option for super users to show (super) users only a message "they need to get in touch with sysadmin to invalidate data" may be useful. You wouldn't want any user, including super user to play around with that when the site is really a high traffic website.

**Comment by tassoman** [comment]
Can be set any arbitrary counts as "resource extensive" ?  
In that case, you can return a direct feedback before instancing the operation.
:green_circle:  :yellow_circle:  :red_circle:
